# Generated by Django 3.1.3 on 2024-07-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usernews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=120)),
                ('politics_preference', models.IntegerField(default=0)),
                ('business_preference', models.IntegerField(default=0)),
                ('technology_preference', models.IntegerField(default=0)),
                ('sports_preference', models.IntegerField(default=0)),
                ('entertainment_preference', models.IntegerField(default=0)),
            ],
        ),
    ]
