services:
  airelevancefilterservice:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8020
    ports:
      - 8020:8020
    volumes:
      - .:/app
    networks:
      - my_network

networks:
  my_network:
    external: true