# Generated by Django 3.1.3 on 2024-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('preference', models.TextField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('news_categories', models.JSONField(default=dict)),
                ('preferred_channel', models.CharField(default='email', max_length=255)),
                ('number_of_news_articles', models.IntegerField(default=3)),
                ('language', models.CharField(default='en', max_length=255)),
            ],
        ),
    ]
