services:
  imanagerbackenda:
    build:
      context: .
      dockerfile: Dockerfile
#    command: 'python manage.py runserver 0.0.0.0:8008'
    ports:
      - 8003:8003
    volumes:
      - .:/app
    networks:
      - my_network

networks:
  my_network:
    external: true
